dist: bionic
language: java
jdk:
  - oraclejdk15
branches:
  only:
    - master
env:
  global:
    - MAVEN_OPTS="-XX:MaxPermSize=512m -Xmx2g"
    - CODECOV_TOKEN="57feef7a-8d7c-4d50-82ca-56e5b7e64586"
script: ./build.sh
